version: '3'
services:
  openbmclapi:
    image: zerowolf233/mcim
    environment:
      CLUSTER_ID: ${CLUSTER_ID}
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_PUBLIC_PORT: 4000
      TZ: Asia/Shanghai
#      CLUSTER_IP: ''
    volumes:
    - ./opt/mcim:/opt/mcim/cache
    ports:
    - "4000:4000"
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'
